# Generated by Django 5.2.4 on 2025-07-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('video_title', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
            ],
        ),
    ]
